// Generated by Grafana k6 Studio (1.6.0) on 2025-08-22T04:25:22.467Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";
import { textSummary } from "https://jslib.k6.io/k6-summary/0.0.1/index.js";

export const options = {
  stages: [
    { target: 5, duration: "10s" }
  ]
};

export default function () {


  group('Log in', function () {
    let formData = {
      username: 'pkyaw@dight.ai',
      password: 'Def@u1tPW'
    }
    let contentType = 'application/x-www-form-urlencoded;charset=utf-8'
    let res = http.post('https://aumpintdev.b2clogin.com/aumpintdev.onmicrosoft.com/b2c_1_signin/oauth2/v2.0/authorize?client_id=dce18ad1-7d68-4ee5-8bd3-3d1ee2aea366&scope=https%3A%2F%2Faumpintdev.onmicrosoft.com%2Fauth-api-dev%2Fauth.read%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fapp-dev.auditmypayroll.com.au%2Fsignin-oidc&client-request-id=0198e03d-f709-7015-a5c9-e176c148e90e&response_mode=fragment&client_info=1&nonce=0198e03d-f70a-7279-a1a0-18d9bd7abd3e&state=eyJpZCI6IjAxOThlMDNkLWY3MGEtNzk2MS05OGMwLWJkMWJlZTVhNTMwYyIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D%7Clogin_attempt_1756108814089&x-client-SKU=msal.js.browser&x-client-VER=4.9.1&response_type=code&code_challenge=49syxzHVZP88ontBwloIKC4wBR6-_Ptm8fVuieDujoM&code_challenge_method=S256', formData, { headers: { 'Content-Type': contentType } })
    check(res, {
      'status is 200': (r) => r.status === 200,
    });
    sleep(3);
  });

  group('Dashboard page', function () {
    let res = http.get('https://app-dev.auditmypayroll.com.au/dashboard');
    
    check(res, {
      'status is 200': (r) => r.status === 200,
      'root element is present': (r) => r.body && r.body.includes('id="root"'),
    });
  });
  sleep(1);

  group('Auditer Page', function () {
    let auditerpage = http.get('https://app-dev.auditmypayroll.com.au/payrollauditer');
    check(auditerpage, {
      'status is 200': (r) => r.status === 200,
      'Auditer page is loaded': (r) => r.body && r.body.includes('id="root"'),
    });
  });
  group('Payroll Compliancer Page', function () {
    let compliancerPage = http.get('https://app-dev.auditmypayroll.com.au/payrollcompliancer');
    check(compliancerPage, {
      'status is 200': (r) => r.status === 401,
      'Auditer page is loaded': (r) => r.body && r.body.includes('id="root"'),
    });
  });

}
export function handleSummary(data) {
  return {
    "summary.html": htmlReport(data, { title: "My K6 Test Report" }),
    "stdout": textSummary(data, { indent: " ", enableColors: true }),
  };
}
